version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  python-app:
    build: . 
    container_name: python-app
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql-db # Zależność tylko od MySQL

networks:
  app-network:

volumes:
  mysql-data:
