name: 🐍 Python Code Check

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  lint_and_check_deps:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout code
      uses: actions/checkout@v4

    - name: 🛠️ Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: 📦 Install dependencies
      # Instaluje zależności z requirements.txt
      run: pip install -r requirements.txt
      working-directory: .

    - name: 🔬 Lint and Check Syntax (flake8)
      run: |
        # Instalacja prostego narzędzia do sprawdzania składni/stylu
        pip install flake8
        # Uruchomienie flake8 na głównym pliku aplikacji
        flake8 server.py
      working-directory: .
